/* Copyright(C) 2017-2026, HJD (https://github.com/hjdhjd). All rights reserved.
 *
 * message-types.ts: ESPHome API message type identifiers.
 */

/**
 * ESPHome API message type identifiers for protocol communication.
 *
 * @module protocol/message-types
 */

/**
 * We support almost all of the ESPHome API message types. These message types define the protocol communication between the client and the ESPHome device.
 */
export enum MessageType {

  HELLO_REQUEST                                 = 1,
  HELLO_RESPONSE                                = 2,
  AUTHENTICATION_REQUEST                        = 3,
  CONNECT_REQUEST                               = 3,
  AUTHENTICATION_RESPONSE                       = 4,
  CONNECT_RESPONSE                              = 4,
  DISCONNECT_REQUEST                            = 5,
  DISCONNECT_RESPONSE                           = 6,
  PING_REQUEST                                  = 7,
  PING_RESPONSE                                 = 8,
  DEVICE_INFO_REQUEST                           = 9,
  DEVICE_INFO_RESPONSE                          = 10,
  LIST_ENTITIES_REQUEST                         = 11,
  LIST_ENTITIES_BINARY_SENSOR_RESPONSE          = 12,
  LIST_ENTITIES_COVER_RESPONSE                  = 13,
  LIST_ENTITIES_FAN_RESPONSE                    = 14,
  LIST_ENTITIES_LIGHT_RESPONSE                  = 15,
  LIST_ENTITIES_SENSOR_RESPONSE                 = 16,
  LIST_ENTITIES_SWITCH_RESPONSE                 = 17,
  LIST_ENTITIES_TEXT_SENSOR_RESPONSE            = 18,
  LIST_ENTITIES_DONE_RESPONSE                   = 19,
  SUBSCRIBE_STATES_REQUEST                      = 20,
  BINARY_SENSOR_STATE_RESPONSE                  = 21,
  COVER_STATE_RESPONSE                          = 22,
  FAN_STATE_RESPONSE                            = 23,
  LIGHT_STATE_RESPONSE                          = 24,
  SENSOR_STATE_RESPONSE                         = 25,
  SWITCH_STATE_RESPONSE                         = 26,
  TEXT_SENSOR_STATE_RESPONSE                    = 27,
  SUBSCRIBE_LOGS_REQUEST                        = 28,
  SUBSCRIBE_LOGS_RESPONSE                       = 29,
  COVER_COMMAND_REQUEST                         = 30,
  FAN_COMMAND_REQUEST                           = 31,
  LIGHT_COMMAND_REQUEST                         = 32,
  SWITCH_COMMAND_REQUEST                        = 33,
  SUBSCRIBE_HOMEASSISTANT_SERVICES_REQUEST      = 34,
  HOMEASSISTANT_SERVICE_RESPONSE                = 35,
  GET_TIME_REQUEST                              = 36,
  GET_TIME_RESPONSE                             = 37,
  SUBSCRIBE_HOME_ASSISTANT_STATES_REQUEST       = 38,
  SUBSCRIBE_HOME_ASSISTANT_STATE_RESPONSE       = 39,
  HOME_ASSISTANT_STATE_RESPONSE                 = 40,
  LIST_ENTITIES_SERVICES_RESPONSE               = 41,
  EXECUTE_SERVICE_REQUEST                       = 42,
  LIST_ENTITIES_CAMERA_RESPONSE                 = 43,
  CAMERA_IMAGE_RESPONSE                         = 44,
  CAMERA_IMAGE_REQUEST                          = 45,
  LIST_ENTITIES_CLIMATE_RESPONSE                = 46,
  CLIMATE_STATE_RESPONSE                        = 47,
  CLIMATE_COMMAND_REQUEST                       = 48,
  LIST_ENTITIES_NUMBER_RESPONSE                 = 49,
  NUMBER_STATE_RESPONSE                         = 50,
  NUMBER_COMMAND_REQUEST                        = 51,
  LIST_ENTITIES_SELECT_RESPONSE                 = 52,
  SELECT_STATE_RESPONSE                         = 53,
  SELECT_COMMAND_REQUEST                        = 54,
  LIST_ENTITIES_SIREN_RESPONSE                  = 55,
  SIREN_STATE_RESPONSE                          = 56,
  SIREN_COMMAND_REQUEST                         = 57,
  LIST_ENTITIES_LOCK_RESPONSE                   = 58,
  LOCK_STATE_RESPONSE                           = 59,
  LOCK_COMMAND_REQUEST                          = 60,
  LIST_ENTITIES_BUTTON_RESPONSE                 = 61,
  BUTTON_COMMAND_REQUEST                        = 62,
  LIST_ENTITIES_MEDIA_PLAYER_RESPONSE           = 63,
  MEDIA_PLAYER_STATE_RESPONSE                   = 64,
  MEDIA_PLAYER_COMMAND_REQUEST                  = 65,
  SUBSCRIBE_VOICE_ASSISTANT_REQUEST             = 89,
  VOICE_ASSISTANT_REQUEST                       = 90,
  VOICE_ASSISTANT_RESPONSE                      = 91,
  VOICE_ASSISTANT_EVENT_RESPONSE                = 92,
  LIST_ENTITIES_ALARM_CONTROL_PANEL_RESPONSE    = 94,
  ALARM_CONTROL_PANEL_STATE_RESPONSE            = 95,
  ALARM_CONTROL_PANEL_COMMAND_REQUEST           = 96,
  LIST_ENTITIES_TEXT_RESPONSE                   = 97,
  TEXT_STATE_RESPONSE                           = 98,
  TEXT_COMMAND_REQUEST                          = 99,
  LIST_ENTITIES_DATE_RESPONSE                   = 100,
  DATE_STATE_RESPONSE                           = 101,
  DATE_COMMAND_REQUEST                          = 102,
  LIST_ENTITIES_TIME_RESPONSE                   = 103,
  TIME_STATE_RESPONSE                           = 104,
  TIME_COMMAND_REQUEST                          = 105,
  VOICE_ASSISTANT_AUDIO                         = 106,
  LIST_ENTITIES_EVENT_RESPONSE                  = 107,
  EVENT_RESPONSE                                = 108,
  LIST_ENTITIES_VALVE_RESPONSE                  = 109,
  VALVE_STATE_RESPONSE                          = 110,
  VALVE_COMMAND_REQUEST                         = 111,
  LIST_ENTITIES_DATETIME_RESPONSE               = 112,
  DATETIME_STATE_RESPONSE                       = 113,
  DATETIME_COMMAND_REQUEST                      = 114,
  VOICE_ASSISTANT_TIMER_EVENT_RESPONSE          = 115,
  LIST_ENTITIES_UPDATE_RESPONSE                 = 116,
  UPDATE_STATE_RESPONSE                         = 117,
  UPDATE_COMMAND_REQUEST                        = 118,
  VOICE_ASSISTANT_ANNOUNCE_REQUEST              = 119,
  VOICE_ASSISTANT_ANNOUNCE_FINISHED             = 120,
  VOICE_ASSISTANT_CONFIGURATION_REQUEST         = 121,
  VOICE_ASSISTANT_CONFIGURATION_RESPONSE        = 122,
  VOICE_ASSISTANT_SET_CONFIGURATION             = 123,
  NOISE_ENCRYPTION_SET_KEY_REQUEST              = 124,
  NOISE_ENCRYPTION_SET_KEY_RESPONSE             = 125
}
